spring.application.name=email-write-1
 
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent

gemini.api.key=AIzaSyDb0GjGp5QxDEuk52wvBCouGhbjYVhOmGE